name: Codecov
  uses: codecov/codecov-action@v1.0.7
  with:
    name:
    token: 9f44a821-9c3a-4adf-8f8f-6f99bc153a11
    file: # optional
    flags: # optional
    env_vars: # optional
    fail_ci_if_error: # optional
